### ISSUE TITLE
Code style improvements

### ISSUE THREAD

**Issue by specialkk** [MistaBibi/Steins-Gate-Discord-Bot#1]
https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L1 Currently you have a few problems that would normally be errors in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode). You should either opt in to strict mode with `'use strict';` at the top of the file or use [ESM](https://www.npmjs.com/package/esm).

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L11 Try to stick to one quote style.

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L18 Just pretend `==` doesn't exist (insert rip on JS type coercion). Stick with `===` and `!==`.

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L12 Yeah, [Standard](https://standardjs.com) exists, but just be consistent with the semicolons at least.

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L24 In strict mode this would throw a `ReferenceError` since `command` hasn't been defined. In loose mode this is an implicit global variable declaration.

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L33 This `.trim()` isn't actually helping anything

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L42-L43 If you're going to have a template string with multiple lines defined on its own line like this, you might as well take advantage the fact they can be multiline within code.
For example:
```javascript
    const helpText = 
`I-It's not like I want you to know how I work or anything, **b-b-baka**!
_Emojis:_
${emojiEntries.join('\n')}
_Commands:_
${commandEntries.join('\n')}`;
```
Also, don't forget the `;`.

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L49-L50 These `let` declarations can be `const`.

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L51 This is another implicit global variable declaration 😕.

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/utils.js#L7-L12 This whole function can be accomplished with a single regex on the plain string message without splitting it into words first. Also naming an argument `str` that isn't really a string but instead an unparsed RegExp is kind of misleading. If it is actually just a string, use `===` instead of `String.prototype.match()`. Otherwise I'd rename the argument to `pattern` or similar.

Also, tf is a `var` doing in there?

https://github.com/MistaBibi/Steins-Gate-Discord-Bot/blob/0b3cfaf348dc716bd30417548992f64ce4728e9f/SGBot.js#L53-L54 This is a pretty weird way of looking up a key name in a map 😛. You should already have the emoji name from a capture group. Just do `config.emojis[emoji]`.

All right that should be everything aside for some repeat offenses I didn't bother pointing out. You made pretty good of use of array maps and seem to be pretty aware of the important string functions. I recommend that you set up ESLint for more instant feedback on code quality 😛.

**Comment by MistaBibi** [comment]
> This whole function can be accomplished with a single regex on the plain string message without splitting it into words first.

Yeah my first idea was to split it so I could look for emoji usage by word...I guess `.match()` would have been a better use here. I think I might just remove this method entirely.
> Also, tf is a var doing in there?

Not sure what the issue with var is here? I assumed it was the equivalent of a counter in a Java for loop. Method is being removed anyways though.

Looks like I tried applying too much Java to Javascript
*Please excuse my JS incompetency and thanks for reviewing*
